"""Generate the browser lookup's expected answers from the Python resolver.

    uv run python scripts/web_lookup_fixture.py

The interface resolves an exact coordinate to a forecast cell in the browser, using the
projection parameters and arithmetic published in `grid.json`. If proj4js and pyproj
disagree anywhere, or if the published formula drifts from the resolver that assigned the
cells, a reader sees a neighboring cell's temperature under their own neighborhood's
name. Nothing about that looks broken on screen, so it needs a test rather than a look.

This writes the Python answers to a fixture the TypeScript suite asserts against. The
grid definition travels with them, so the two sides are compared on one build's contract.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
from affine import Affine
from rasterio.windows import Window

from feelslike_la.config import BUILD_DIR, ROOT
from feelslike_la.sample import CellResolver

FIXTURE = ROOT / "web" / "test" / "fixtures" / "cell_expectations.json"

# A grid of coordinates across the county, dense enough that many cases land close to a
# cell boundary, which is where two projection libraries would disagree first.
SAMPLE_STEPS = 30


def published_build() -> Path:
    pointer = json.loads((BUILD_DIR / "latest.json").read_text())
    return BUILD_DIR / Path(pointer["manifest"]).parent


def resolver_from_grid(grid: dict) -> CellResolver:
    """Rebuild the resolver from published values only, so the fixture tests the contract."""
    a, b, c, d, e, f = grid["window_transform"]
    window = Window(**grid["window"])
    source = Affine(a, b, c - window.col_off * a, d, e, f - window.row_off * e)
    return CellResolver(
        grid["crs_wkt"],
        source,
        grid["source_grid"]["width"],
        grid["source_grid"]["height"],
        window=window,
    )


def main() -> None:
    build = published_build()
    grid = json.loads((build / "grid.json").read_text())
    places = json.loads((build / "places.json").read_text())["places"]
    forecasts = json.loads((build / "cell_forecasts.json").read_text())
    known = {cell["cell_id"] for cell in forecasts["cells"]}
    resolver = resolver_from_grid(grid)

    coordinates: list[tuple[float, float, str]] = [
        (
            place["reference_point"]["longitude"],
            place["reference_point"]["latitude"],
            place["slug"],
        )
        for place in places
    ]

    longitudes = [cell["longitude"] for cell in forecasts["cells"]]
    latitudes = [cell["latitude"] for cell in forecasts["cells"]]
    for longitude in np.linspace(min(longitudes), max(longitudes), SAMPLE_STEPS):
        for latitude in np.linspace(min(latitudes), max(latitudes), SAMPLE_STEPS):
            coordinates.append((round(float(longitude), 6), round(float(latitude), 6), "grid"))

    cases = []
    for longitude, latitude, origin in coordinates:
        try:
            cell = resolver.resolve(longitude, latitude)
        except ValueError:
            continue
        cases.append(
            {
                "longitude": longitude,
                "latitude": latitude,
                "origin": origin,
                "cell_id": cell.cell_id,
                "published": cell.cell_id in known,
            }
        )

    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(
        json.dumps(
            {
                "note": "Generated by scripts/web_lookup_fixture.py; regenerate if the grid changes.",
                "grid_fingerprint": grid["grid_fingerprint"],
                "grid": {
                    key: grid[key]
                    for key in ("proj4", "source_grid", "window", "window_transform")
                },
                "cases": cases,
            },
            indent=1,
        )
        + "\n"
    )
    inside = sum(1 for case in cases if case["published"])
    print(f"wrote {len(cases)} cases ({inside} inside published coverage) to {FIXTURE}")


if __name__ == "__main__":
    main()
